### ISSUE TITLE
Rename 7580720.bin to i7-5775C.bin or similar

### ISSUE THREAD

**Issue by jplatte** [bgw/bdw-ucode-update-tool#1]
I checked all four binaries in the 5x75c directory, and the one that iucode_tool reports as having a microcode for my processor (and works perfectly) is `7580720.bin`.

I checked all files as documented in the [arch wiki](https://wiki.archlinux.org/index.php/Microcode#Detecting_available_microcode_update) and only this one was reported as having a microcode update for my processor:

```
[jonas@jp-desktop 5x75c]$ iucode_tool -tb -lS 7580720.bin
iucode_tool: system has processor(s) with signature 0x00040671
selected microcodes:
001: sig 0x00040671, pf mask 0x22, 2015-06-19, rev 0x0012, size 11264
[jonas@jp-desktop 5x75c]$ iucode_tool -tb -lS 7591984.bin
iucode_tool: system has processor(s) with signature 0x00040671
selected microcodes:
[jonas@jp-desktop 5x75c]$ iucode_tool -tb -lS 7613488.bin
iucode_tool: system has processor(s) with signature 0x00040671
selected microcodes:
[jonas@jp-desktop 5x75c]$ iucode_tool -tb -lS 7636016.bin
iucode_tool: system has processor(s) with signature 0x00040671
selected microcodes:
```

**Comment by bgw** [comment]
I did the same thing on my i5-5675C, and it seems that `7580720.bin` is also the only matching version on my machine. I'll verify that only installing that one file updates my microcode, and if so, I'll rename it and get rid of the other files.

If anyone has an i7-5700HQ, I'd like to hear which file(s) iucode-tool identifies as matching your system. Based on release dates, I suspect 2563264.bin would be it.

**Comment by bgw** [comment]
@jplatte Thanks.
