### ISSUE TITLE
This tool SHOULD support windows!

### ISSUE THREAD

**Issue by ghost** [bgw/bdw-ucode-update-tool#2]
This tool can update microcode on windows environ.
https://labs.vmware.com/flings/vmware-cpu-microcode-update-driver

While intel provide the `microcode.dat`
Just simple script that required for `5x75c.bin` binary file to `microcode.dat`

So i just write dirty script that convert thing. (and untrusted microcode.dat file)
https://gist.github.com/EcmaXp/506e6255a654dd6f01a8

I did tested on Windows 10; with i7-5775C and Z97I-PLUS.
http://valid.x86.fr/qswsv1

Thanks.

**Comment by bgw** [comment]
I'll add a link in the README regarding this. I also wouldn't be concerned with trusting the .dat file, because it's pretty much impossible for anyone to make a malicious microcode update. However, I have independently confirmed that running that python script gives the same .dat file.

If you've got the time, would you be willing to make a more step-by-step writeup, presumably for less technically competent Windows users?

**Comment by tssge** [comment]
This made my day. I can't find words to thank you enough!

Now VirtualBox, Dota2 and all other stuff runs fine on my Windows machine. Big thanks to @bgw and @EcmaXp !

**Comment by bgw** [comment]
@tssge Glad to hear it! Would you be willing to make a step-by-step guide for non-technical users?

**Comment by ghost** [comment]
Before starting update microcode, please read https://labs.vmware.com/flings/vmware-cpu-microcode-update-driver
1. Download file from VMware site (above? url) and extract the files contained within the zip.
2. Download https://git.kernel.org/cgit/linux/kernel/git/firmware/linux-firmware.git/plain/amd-ucode/microcode_amd.bin and https://git.kernel.org/cgit/linux/kernel/git/firmware/linux-firmware.git/plain/amd-ucode/microcode_amd_fam15h.bin and place to same directory as where the files from .1 were placed.
*\* Because VMware microcode update driver require that 2 files even if you don't have AMD CPU.
3. Download https://github.com/bgw/bdw-ucode-update-tool/raw/master/0x13.dat and rename to `microcode.dat`; and place to same directory as where the files from #1 were placed.
4. Right click the `install.bat` file and left click 'Run as an Administrator'; It should work!
5. After everything is done, you can check "Event Viewer" for check update status.
*\* When everything is working fine, now you can use virtual machine with Linux or play Source Engine game even if reboot windows.

**Comment by tssge** [comment]
@EcmaXp You were faster than me! But yeah, you don't need to download AMD microcode, I just made empty files for those 2 and it worked.

**Comment by bgw** [comment]
Thanks for the help @EcmaXp and @tssge!
